### ISSUE TITLE
Updates for introducing alta

### ISSUE THREAD

**Issue by syoh** [UCSB-PSTAT/computing-wiki#8]
- [x] Change references of `denali` to `alta`
- [x] Let's make the codelabs specific to `alta` and just remote devcontainer to simplify the steps
- [x] SSH Setup: If we separate git/github, I believe the whole setup could be simpler.  
  - No git installation, no need for github account
  - VPN doesn't seem to be needed to connect to `alta`
  - Use powershell (built into windows 10 and 11) to [generate ssh keys](https://learn.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement#user-key-generation)
  - Since user accounts will be local accounts, reference to NETID and password can be removed.
- [x] Dev Containers with VS Code
  - Update prereqs to be consistent with SSH Setup
  - Update Docker link to https://www.docker.com/products/docker-desktop/
  - Removing binder and using `copier` on `alta`
- [x] Create and link test-user signup form
- [x] Join [PSTAT Research Computing Users](https://chat.google.com/room/AAAAR6wMcN0?cls=4) group

What od you think?

**Comment by 392781** [comment]
Comment out initial setup and instead create "Setup" single codelab specifying:
* Join PSTAT Research Computing group on Google (link)
* SSH generation (Powershell) **COMPLETE THIS**.
* fill out form (link **create this**: Name/NETID/etc.etc. (details onslack)).
* mention waiting period, setup vscode in the mean time, 
* connecting to alta
* running copier
* connecting to dev container

**Comment by 392781** [comment]
Almost done with this.  Just updated the Google Doc, needs some updated screenshots and then I'll be able to regenerate the documentation!

**Comment by 392781** [comment]
This is completed.
